export interface CalendarEvent {
    id: number;
    name: string;
    category: string;
    date: string;
    timeFrom: string;
    timeUntil: string;
}

// API response types
export interface ApiEventsResponse {
  events: CalendarEvent[];
  total: number;
  hasMore?: boolean;
}

// Form types for creating/editing
export interface CreateEventRequest {
  title: string;
  description?: string;
  date: string;
  startTime?: string;
  endTime?: string;
  color?: string;
  category?: string;
  // id is generated by the server, so not included
}

export interface UpdateEventRequest extends Partial<CreateEventRequest> {
  id: string; // Required for updates
}